org: nithinibhandari1999
app: my-express-application
service: my-express-application
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: ap-south-1

functions:
  app:
    handler: index.handler
    events:
      - httpApi:
        method: "*"
        path: "*"

plugins:
  - serverless-offline